import type { Metadata } from "next";
import {
  Inter,
  Montserrat,
  Open_Sans,
  Poppins,
  Roboto,
} from "next/font/google";
import "./globals.css";

const inter = Montserrat({ subsets: ["latin"], weight: ["500"] });

export const metadata: Metadata = {
  title: "Central de Livros",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
